version: 2.1
jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
                 sudo apt-get update
                 sudo docker build -t web .
                 sudo docker run web:latest